#!/usr/bin/env python3
# mypy: disallow-untyped-defs
# pylint: disable=C0114,C0116
######################################################################

import argparse
import re
import subprocess
import sys
from typing import Iterable

SUPPRESSES = [
    "**********",
    "E0602: Undefined variable 'test' (undefined-variable)",
    "E0602: Undefined variable 're' (undefined-variable)",
    "E0602: Undefined variable 'os' (undefined-variable)",
    "E0602: Undefined variable 'glob' (undefined-variable)",
    "W0611: Unused import vltest_bootstrap (unused-import)",
]

######################################################################


def process(lines: Iterable[str]) -> int:
    anymsg = False
    suppressed_status = 0
    for line in lines:
        line = line.rstrip()
        show = True
        for msg in SUPPRESSES:
            if msg in line:
                show = False
                diagnostic = re.match(r'^.+:\d+:\d+: ([A-Z]\d{4}): ', line)
                if diagnostic and diagnostic.group(1) == 'E0602':
                    suppressed_status |= 2
                elif diagnostic and diagnostic.group(1) == 'W0611':
                    suppressed_status |= 4
                continue
        if show:
            print(line)
            anymsg = True

    if anymsg:
        sys.exit("%Error: See messages above")
    return suppressed_status


def run_pylint(command: list[str]) -> None:
    with subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                          text=True) as child:
        assert child.stdout is not None
        try:
            suppressed_status = process(child.stdout)
        finally:
            status = child.wait()
    # Pylint reports a bitmask. Only diagnostics actually suppressed above may
    # account for a nonzero exit; fatal, usage, signals and silent failures fail.
    if status != suppressed_status:
        sys.exit(f"%Error: Pylint exited with status {status}, expected {suppressed_status}"
                 " from suppressed diagnostics")


#######################################################################
#######################################################################

parser = argparse.ArgumentParser(
    allow_abbrev=False,
    formatter_class=argparse.RawDescriptionHelpFormatter,
    description="""lint_py_test_filter is used to filter
pylint output for expected errors in Verilator test_regress/*.py tests.""",
    epilog="""This program is free software; you can redistribute it and/or modify it
under the terms of either the GNU Lesser General Public License Version 3
or the Perl Artistic License Version 2.0.

SPDX-FileCopyrightText: 2024-2026 Wilson Snyder
SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0
""")

parser.add_argument('--debug', action='store_true', help='enable debug')
parser.add_argument('--pylint', nargs=argparse.REMAINDER, help='pylint command and arguments')

Args = parser.parse_args()
if Args.pylint is not None:
    if not Args.pylint:
        parser.error('--pylint requires a command')
    run_pylint(Args.pylint)
else:
    process(sys.stdin)

######################################################################
# Local Variables:
# compile-command: "cd .. ; make lint-py-pylint-tests"
# End:
